server:
  port: 8080
#MongoDB configs uri: mongodb://myplantdbuser:myplantpass@ds111461.mlab.com:11461/heroku_qm1q82dh
spring:
  data:
    mongodb:
      host: ds111461.mlab.com
      port: 11461
      database: heroku_qm1q82dh
      username: myplantdbuser
      password: myplantpass

# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html # ;charset=<encoding> is added
    cache: false # set to false for hot refresh
---

spring:
    profiles: development

---
spring:
    profiles: locale
