spring:
  config:
    import: optional:file:./.env[.properties]
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:MyPlant}

  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html # ;charset=<encoding> is added
    cache: false # set to false for hot refresh
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
  devtools:
    livereload:
      enabled: true

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

#MongoDB configs uri: mongodb://myplantdbuser:myplantpass@ds111461.mlab.com:11461/heroku_qm1q82dh
#mongodb://rekaandrii_db_user:<db_password>@ac-uzt1wez-shard-00-00.jkglvhb.mongodb.net:27017,ac-uzt1wez-shard-00-01.jkglvhb.mongodb.net:27017,ac-uzt1wez-shard-00-02.jkglvhb.mongodb.net:27017/?ssl=true&replicaSet=atlas-6wrl1y-shard-0&authSource=admin&appName=MyPlant
---

spring:
    profiles: development

---
spring:
    profiles: locale
